import {
  AppWindow,
  Bot,
  Box,
  ChartLine,
  Cloud,
  Container,
  Database,
  Globe,
  HardDrive,
  Layers,
  Mail,
  Network,
  Server,
  Shield,
  Smartphone,
  SquareFunction,
  User,
  Waypoints,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { ArchitectureIcon } from '../../../../shared/visualization/infographic-spec';

/** 아이콘 종류 → lucide 아이콘 (ISC). Spec의 ARCHITECTURE_ICONS와 함께 늘린다. */
export const ARCHITECTURE_ICON: Record<ArchitectureIcon | 'generic', LucideIcon> = {
  user: User,
  client: AppWindow,
  mobile: Smartphone,
  internet: Cloud,
  cdn: Globe,
  'load-balancer': Network,
  gateway: Waypoints,
  server: Server,
  container: Container,
  function: SquareFunction,
  database: Database,
  cache: Zap,
  storage: HardDrive,
  queue: Layers,
  ai: Bot,
  mail: Mail,
  security: Shield,
  monitoring: ChartLine,
  generic: Box,
};
